config/routes.rb
Rails.application.routes.draw do
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :brands
    resources :product_types
    get 'admin_product_types' => 'product_types#admin_index', as: 'admin_product_types'
    resources :customers
    devise_for :admins
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :customers
    get 'customers_admin' => 'customers#admin_index', as: 'admin_customers'
    get 'customer_admin' => 'customers#admin_show', ad: 'admin_customer'
    resources :articles
    resources :photos
    resources :products
    resources :attachments, except: :show
    resources :marketapps, except: :show
    resources :histories, except: [:show, :index]
    #contact
    get 'contacts/new' => 'contacts#new', as: 'new_contact'
    post 'contacts' => 'contacts#create', as: 'contacts'
    # product browser
    get 'product-browser' => 'product_browser#browser', as: 'pb'
    get 'product-browser/product-type/:id' => 'product_browser#product_types', as: 'pb_pt'
    get 'product-browser/brand/:id' => 'product_browser#brands', as: 'pb_b'



    # pages
    # the code right below is alternative to %get 'pages/home' => 'pages#home', as: "home"%
    root 'pages#home'
    get 'pages/about-us' => 'pages#aboutUs', as: 'about_us'
    get 'pages/a-letter-from-the-ceo' => 'pages#ceoLetter', as: 'ceo_letter'
    get 'pages/company-history' => 'histories#index', as: 'company_history'
    get 'pages/contact-us' => 'pages#contactUs', as: 'contact_us'
    get 'pages/careers' => 'pages#careers', as: 'careers'
    get 'pages/locations' => 'pages#locations', as: 'locations'
    get 'pages/downloads' => 'pages#downloads', as: 'downloads'
    get 'pages/downloads_search' => 'pages#downloads_search', as: 'downloads_search'
    get 'pages/search' => 'pages#search', as: 'search'

    # markets
    get 'markets/' => 'markets#index', as: 'allMarkets'

    # heritages link
    get 'heritages/:heritage' => 'products#index', as: :heritage

    # locale redirect
    get "*path", to: "pages#not_found"
  end

  # locale redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,
          :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # photo
  has_many :photos, as: :images ,dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  # validation
  validates :title, :summary, presence: true
  # globalize
  translates :title, :string
  translates :summary, :text
  # globalize form attr
  globalize_accessors attributes: [:title, :summary]
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :file_path, FileUploader
end

app/models/brand.rb
class Brand < ActiveRecord::Base
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    has_many :brand_product_types, dependent: :destroy
    has_many :product_types, through: :brand_product_types
    has_many :products, through: :product_types
    validates :name, presence: true
    validates :photos, presence: true
    validates :background_pic, presence: true

    mount_uploader :background_pic, PicsUploader

    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    def title
        self.name
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :photos, as: :images, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name, :presence => true
  validates :name, :uniqueness => true

  # globalize
  translates :name, :string
  # globalize form attr
  globalize_accessors :locales => [:en, :ko], :attributes => [:name]

end

app/models/history.rb
class History < ApplicationRecord
    # validation
    validates :title, :event_date, presence: true
    # globalize
    translates :title, :string
    # globalize form attr
    globalize_accessors attributes: [:title]
end

app/models/market.rb
class Market < ApplicationRecord
  has_many :marketapps
  translates :name, :string
  globalize_accessors attributes: [:name]

  mount_uploader :banner, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
end

app/models/marketapp.rb
class Marketapp < ApplicationRecord
  belongs_to :market
  translates :name, :string
  globalize_accessors attributes: [:name]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :images, polymorphic: :true
  
  mount_uploader :pics, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_pics

  def crop_pics
    pics.recreate_versions! if crop_x.present?
    puts 'pics recreated'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  belongs_to :brand
  has_many :photos, as: :images, dependent: :destroy
  has_many :subproducts

  # # globalize
  # translates :name, :string
  # translates :summary, :text
  # # globalize form attr
  # globalize_accessors attributes: [:name, :summary]
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
    has_many :brand_product_types
    has_many :brands, :through => :brand_product_types
    has_many :products
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    validates :name, presence: true

    # globalize
    translates :name, :string
    # globalize form attr
    globalize_accessors attributes: [:name]

end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :product
end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :to_crop_obj, only: [:edit, :update]
  before_action :crop_ratio, only: [:create, :update]
  before_action :all_brands, only: [:new, :edit]

  # GET /product_types
  def index
    if admin_signed_in?
      redirect_to "/ko/admin_product_types"
    else
      redirect_to "/"
    end

  end

  def admin_index
    @pt = ProductType.all
  end

  # GET /product_types/1
  def show
    @brands = @product_type.brands
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  def create
   @product_type = ProductType.new(product_type_params)
    if @product_type.save
      if @product_type.photos.present?
        @crop_obj = @product_type
        render "shared/crop"
      else
        redirect_to @product_type
      end
    else
      render :new
    end
  end

  # PATCH/PUT /product_types/1
  def update
    if @product_type.update(product_type_params)
      if @product_type.photos.present?
        render "shared/crop"
      else
        redirect_to @product_type
      end
    else
      render :edit
    end
  end

  def crop

  end

  # DELETE /product_types/1
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    def to_crop_obj
      @crop_obj = @product_type
    end

    def crop_ratio
      @crop_ratio = 0
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def product_type_params
      params.require(:product_type).permit(*ProductType.globalize_attribute_names,  photos_attributes: [:id, :pics, :_destroy, :product_type_id])
    end

    def all_brands
      @brands = Brand.all
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= nested_form_for(@product_type) do |f| %>
  <% if @product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
      <% @product_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h4>한글 제품타입 이름</h4>
    <%= f.text_field :name_ko, class: "text_field" %>
  </div>
  <div class="field">
    <h4>영문 제품타입 이름</h4>
    <%= f.text_field :name_en, class: "text_field" %>
  </div>
  <div class="field">
    <%= f.label :photos, "부수 사진" %>
    <%= f.fields_for :photos do |pf| %>
      <%= pf.file_field :pics, class: "photoInfo" %>
      <%= pf.link_to_remove "삭제하기", class: "photoButton", type: "remove" %>
    <% end %>
    <%= f.link_to_add "추가하기", :photos, class: "photoButton", type: "add" %>
  </div>
  <div class="field">
    <%= f.collection_check_boxes :brand_ids, @brands, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_types/admin_index.html.erb
<h2>제품 타입 리스트</h2>
<% if admin_signed_in? %>
<%= link_to "제품 타입 추가", new_product_type_path %>
<% end %>
<table>
  <thead>
  <tr>
    <th>이름</th>
    <th>수정</th>
    <th>삭제</th>
  </tr>
  </thead>
  <tbody>
  <% if admin_signed_in? %>
  <% @pt.each do |pt| %>
  <tr>
    <td><%= link_to(pt.name, pt) %></td>
    <td><%= link_to("수정하기", edit_product_type_path(pt)) %></td>
    <td><%= link_to("삭제하기", product_type_path(pt), method: :DELETE, confirm: "삭제하시면 연결된 제품들도 삭제됩니다. 정말 삭제하시겠습니까?") %></td>
  </tr>
  <% end %>
  <% end %>s
  </tbody>

</table>

app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t(".title") %></h1>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>

<%= render 'form' %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p>
  이름: <%= @product_type.name %><br/>
  <% if @product_type.photos.present? %>
      <% @product_type.photos.each do |photo| %>
          <%= image_tag photo.pics.url(:logo)%>
      <% end %>
  <% end %>
</p>

app/views/product_types/show.js.erb
$('.products_browser_container').addClass('product_type_activated');
$('#brands_products_container').html("<%= j render(:partial => "show_brands")%>");
if ($('.brands_products_container').hasClass('brand_activated')){
  $('.brands_products_container').removeClass('brand_activated');
}