config/routes.rb
Rails.application.routes.draw do
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :brands
    resources :product_types
    get 'admin_product_types' => 'product_types#admin_index', as: 'admin_product_types'
    resources :customers
    devise_for :admins
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :customers
    get 'customers_admin' => 'customers#admin_index', as: 'admin_customers'
    get 'customer_admin' => 'customers#admin_show', ad: 'admin_customer'
    resources :articles
    resources :photos
    resources :products
    resources :attachments, except: :show
    resources :marketapps, except: :show
    resources :histories, except: [:show, :index]
    #contact
    get 'contacts/new' => 'contacts#new', as: 'new_contact'
    post 'contacts' => 'contacts#create', as: 'contacts'
    # product browser
    get 'product-browser' => 'product_browser#browser', as: 'pb'
    get 'product-browser/product-type/:id' => 'product_browser#product_types', as: 'pb_pt'
    get 'product-browser/brand/:id' => 'product_browser#brands', as: 'pb_b'



    # pages
    # the code right below is alternative to %get 'pages/home' => 'pages#home', as: "home"%
    root 'pages#home'
    get 'pages/about-us' => 'pages#aboutUs', as: 'about_us'
    get 'pages/a-letter-from-the-ceo' => 'pages#ceoLetter', as: 'ceo_letter'
    get 'pages/company-history' => 'histories#index', as: 'company_history'
    get 'pages/contact-us' => 'pages#contactUs', as: 'contact_us'
    get 'pages/careers' => 'pages#careers', as: 'careers'
    get 'pages/locations' => 'pages#locations', as: 'locations'
    get 'pages/downloads' => 'pages#downloads', as: 'downloads'
    get 'pages/downloads_search' => 'pages#downloads_search', as: 'downloads_search'
    get 'pages/search' => 'pages#search', as: 'search'

    # markets
    get 'markets/' => 'markets#index', as: 'allMarkets'

    # heritages link
    get 'heritages/:heritage' => 'products#index', as: :heritage

    # locale redirect
    get "*path", to: "pages#not_found"
  end

  # locale redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,
          :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # photo
  has_many :photos, as: :images ,dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  # validation
  validates :title, :summary, presence: true
  # globalize
  translates :title, :string
  translates :summary, :text
  # globalize form attr
  globalize_accessors attributes: [:title, :summary]
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :file_path, FileUploader
end

app/models/brand.rb
class Brand < ActiveRecord::Base
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    has_many :brand_product_types, dependent: :destroy
    has_many :product_types, through: :brand_product_types
    has_many :products, through: :product_types
    validates :name, presence: true
    validates :photos, presence: true
    validates :background_pic, presence: true

    mount_uploader :background_pic, PicsUploader

    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    def title
        self.name
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :photos, as: :images, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name, :presence => true
  validates :name, :uniqueness => true

  # globalize
  translates :name, :string
  # globalize form attr
  globalize_accessors :locales => [:en, :ko], :attributes => [:name]

end

app/models/history.rb
class History < ApplicationRecord
    # validation
    validates :title, :event_date, presence: true
    # globalize
    translates :title, :string
    # globalize form attr
    globalize_accessors attributes: [:title]
end

app/models/market.rb
class Market < ApplicationRecord
  has_many :marketapps
  translates :name, :string
  globalize_accessors attributes: [:name]

  mount_uploader :banner, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
end

app/models/marketapp.rb
class Marketapp < ApplicationRecord
  belongs_to :market
  translates :name, :string
  globalize_accessors attributes: [:name]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :images, polymorphic: :true
  
  mount_uploader :pics, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_pics

  def crop_pics
    pics.recreate_versions! if crop_x.present?
    puts 'pics recreated'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  belongs_to :brand
  has_many :photos, as: :images, dependent: :destroy
  has_many :subproducts

  # # globalize
  # translates :name, :string
  # translates :summary, :text
  # # globalize form attr
  # globalize_accessors attributes: [:name, :summary]
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
    has_many :brand_product_types
    has_many :brands, :through => :brand_product_types
    has_many :products
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    validates :name, presence: true

    # globalize
    translates :name, :string
    # globalize form attr
    globalize_accessors attributes: [:name]

end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :product
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :to_crop_obj, only: [:edit, :update]
  before_action :crop_ratio, only: [:create, :update]
  # GET /articles
  def index
    @articles = Article.all
  end

  # GET /articles/1
  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(new_article_params)
      if @article.save
        if @article.photos.present?
          @crop_obj = @article
          render "shared/crop"
        else
          redirect_to @article
        end
      else
        render :new
      end
  end

  def crop

  end

  def edit
  end

  def update
      if @article.update(new_article_params)
        if @article.photos.present?
          render "shared/crop"
        else
          redirect_to @article
        end
      else
        render :edit
      end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end

private
  def set_article
    @article = Article.find(params[:id])
  end

  def to_crop_obj
    @crop_obj = @article
  end

  def crop_ratio
    @crop_ratio = 2.2222
  end

  def new_article_params
    params.require(:article).permit(*Article.globalize_attribute_names, photos_attributes: [:id, :pics, :_destroy, :article_id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/articles/_form.html.erb
<%= nested_form_for(@article) do |f| %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "에러들") %> 때문에 저장하지 못했습니다:</h2>
          <ul>
          <% @article.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
    <% end %>
    <div class="translationForm">
        <div class="koreanForm">
            <h3>한글</h3>
            <div>
                <%= f.label :title_ko, "한글 제목" %>
                <%= f.text_field :title_ko %>
            </div>
            <div>
                <label for="body">한글 내용</label>
                <%= f.text_area :summary_ko, class: "articleBody" %>
            </div>
        </div>
        <div class="enlgishForm">
            <h3>영문</h3>
            <div>
                <%= f.label :title_en, "영문 제목" %>
                <%= f.text_field :title_en %>
            </div>
            <div>
                <label for="body">영문 내용</label>
                <%= f.text_area :summary_en, class: "articleBody" %>
            </div>
        </div>
    </div>
    <div>
        <%= f.submit "등록하기" %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<div class="small-12 large-12 columns">
    <h1>뉴스 수정하기</h1>
    
    <%= render partial: "form" %>
    
</div>

app/views/articles/index.html.erb
<div class="content-container articles">
  <div class="page-image-container">
    <div class="page-image articles">
      <h2 class="page-image-title"><%= title t(".title") %></h2>
    </div>
  </div>
  <h2 class="page-title"><%= title t(".title") %></h2>
  <% if admin_signed_in? %>
    <div><%= link_to "뉴스 추가하기", new_article_path %></div>
  <% end %>
  <table class="articles-index">
    <thead>
      <tr>
        <th class="articles-th-title"><%= t('.tableTitle') %></th>
        <th class="articles-th-date"><%= t('.tableDate') %></th>
        <% if admin_signed_in? %>
          <th>수정?</th>
          <th>삭제?</th>
        <% end %>
      <tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td class="articles-td-title"><%= link_to article.title.titleize, article_path(article) %></td>
          <td class="articles-td-date"><%= article.updated_at.strftime("%Y-%m-%d") %></td>
          <% if admin_signed_in? %>
          <td><%= link_to "수정하기", edit_article_path(article) %></td>
          <td><%= link_to "삭제하기", article_path(article), method: :DELETE, data:{confirm: "정말 삭제하시겠습니까?"}%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/articles/new.html.erb
<div class="small-12 large-12 columns">
    <h1>뉴스 추가하기</h1>

    <%= render partial: "form" %>

</div>

app/views/articles/show.html.erb
<!--<div class="photo-area articles">-->
<!--    <img src="http://www.coanews.org/liies/2014/11/01.jpg">-->
<!--    <h1><%# t("articles.index.title") %></h1>-->
<!--</div>-->
<div class="content-container articles">
    <div class="page-image-container">
        <div class="page-image articles">
            <h2 class="page-image-title"><%= title t(".title") %></h2>
        </div>
    </div>
    <% if admin_signed_in? %>
        <%= link_to '삭제하기', article_path(@article), method: :DELETE, data:{ confirm: "이 뉴스를 삭제 하시겠습니까?"}%> |
        <%= link_to '수정하기', edit_article_path(@article) %> |
    <% end %>
    <%= link_to t("navigation.back"), articles_path %>

    <h3 class="article-title"><%= title @article.title.titleize %></h3>
    <p class="article-date"><%= @article.updated_at.strftime("%Y-%m-%d") %></p>
    <!--if image is not nil-->
    <% if @article.photos.present? %>
        <% if @article.photos.count < 1 %>
            <div class="photo-area article">
                <%= image_tag @article.photos.first.pics.url(:large) %>
            </div>
        <% else %>
            <div class="orbit orbit-area homepage" role="region" aria-label="Favorite Space Pictures" data-orbit data-options="animInFromLeft:fade-in; animInFromRight:fade-in; animOutToLeft:fade-out; animOutToRight:fade-out;">
                <ul class="orbit-container contents">
                    <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
                    <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
                    <% @article.photos.each do |photo| %>
                      <li class="orbit-slide">
                        <%= image_tag photo.pics.url(:large), class: "orbit-image" %>
                      </li>
                    <% end %>
                </ul>
                <nav class="orbit-bullets">
                    <% @article.photos.each.with_index do |photo, index| %>
                        <button data-slide="<%= index %>"><span class="show-for-sr"><%= photo.pics %></span></button>
                    <% end %>
                </nav>
            </div><!--orbit-->
        <% end %>
    <% end %>
    <div class="article-body"><%= @article.summary.html_safe %></div>
</div>