config/routes.rb
Rails.application.routes.draw do
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :brands
    resources :product_types
    get 'admin_product_types' => 'product_types#admin_index', as: 'admin_product_types'
    resources :customers
    devise_for :admins
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :customers
    get 'customers_admin' => 'customers#admin_index', as: 'admin_customers'
    get 'customer_admin' => 'customers#admin_show', ad: 'admin_customer'
    resources :articles
    resources :photos
    resources :products
    resources :attachments, except: :show
    resources :marketapps, except: :show
    resources :histories, except: [:show, :index]
    #contact
    get 'contacts/new' => 'contacts#new', as: 'new_contact'
    post 'contacts' => 'contacts#create', as: 'contacts'
    # product browser
    get 'product-browser' => 'product_browser#browser', as: 'pb'
    get 'product-browser/product-type/:id' => 'product_browser#product_types', as: 'pb_pt'
    get 'product-browser/brand/:id' => 'product_browser#brands', as: 'pb_b'



    # pages
    # the code right below is alternative to %get 'pages/home' => 'pages#home', as: "home"%
    root 'pages#home'
    get 'pages/about-us' => 'pages#aboutUs', as: 'about_us'
    get 'pages/a-letter-from-the-ceo' => 'pages#ceoLetter', as: 'ceo_letter'
    get 'pages/company-history' => 'histories#index', as: 'company_history'
    get 'pages/contact-us' => 'pages#contactUs', as: 'contact_us'
    get 'pages/careers' => 'pages#careers', as: 'careers'
    get 'pages/locations' => 'pages#locations', as: 'locations'
    get 'pages/downloads' => 'pages#downloads', as: 'downloads'
    get 'pages/downloads_search' => 'pages#downloads_search', as: 'downloads_search'
    get 'pages/search' => 'pages#search', as: 'search'

    # markets
    get 'markets/' => 'markets#index', as: 'allMarkets'

    # heritages link
    get 'heritages/:heritage' => 'products#index', as: :heritage

    # locale redirect
    get "*path", to: "pages#not_found"
  end

  # locale redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,
          :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # photo
  has_many :photos, as: :images ,dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  # validation
  validates :title, :summary, presence: true
  # globalize
  translates :title, :string
  translates :summary, :text
  # globalize form attr
  globalize_accessors attributes: [:title, :summary]
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :file_path, FileUploader
end

app/models/brand.rb
class Brand < ActiveRecord::Base
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    has_many :brand_product_types, dependent: :destroy
    has_many :product_types, through: :brand_product_types
    has_many :products, through: :product_types
    validates :name, presence: true
    validates :photos, presence: true
    validates :background_pic, presence: true

    mount_uploader :background_pic, PicsUploader

    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    def title
        self.name
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :photos, as: :images, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name, :presence => true
  validates :name, :uniqueness => true

  # globalize
  translates :name, :string
  # globalize form attr
  globalize_accessors :locales => [:en, :ko], :attributes => [:name]

end

app/models/history.rb
class History < ApplicationRecord
    # validation
    validates :title, :event_date, presence: true
    # globalize
    translates :title, :string
    # globalize form attr
    globalize_accessors attributes: [:title]
end

app/models/market.rb
class Market < ApplicationRecord
  has_many :marketapps
  translates :name, :string
  globalize_accessors attributes: [:name]

  mount_uploader :banner, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
end

app/models/marketapp.rb
class Marketapp < ApplicationRecord
  belongs_to :market
  translates :name, :string
  globalize_accessors attributes: [:name]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :images, polymorphic: :true
  
  mount_uploader :pics, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_pics

  def crop_pics
    pics.recreate_versions! if crop_x.present?
    puts 'pics recreated'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  belongs_to :brand
  has_many :photos, as: :images, dependent: :destroy
  has_many :subproducts

  # # globalize
  # translates :name, :string
  # translates :summary, :text
  # # globalize form attr
  # globalize_accessors attributes: [:name, :summary]
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
    has_many :brand_product_types
    has_many :brands, :through => :brand_product_types
    has_many :products
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    validates :name, presence: true

    # globalize
    translates :name, :string
    # globalize form attr
    globalize_accessors attributes: [:name]

end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :product
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :admin_show, :edit, :update, :destroy]
  before_action :authenticate_admin!, except: [:index, :show]
  before_action :to_crop_obj, only: [:edit, :update]
  before_action :crop_ratio, only: [:create, :update]


  def index
    @customers = Customer.all
  end

  def admin_index
    @customers = Customer.all
  end

  def show
  end

  def admin_show

  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
      if @customer.save
        if @customer.photos.present?
          @crop_obj = @customer
          render "shared/crop"
        else
          render :admin_show
        end
      else
        render :new
      end
  end

  def crop
  end

  def update
      if @customer.update(customer_params)
        if @customer.photos.present?
          render "shared/crop"
        else
          render :admin_show
        end
      else
        render :edit
      end
  end

  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_customer
      @customer = Customer.find(params[:id])
    end

    def to_crop_obj
      @crop_obj = @customer
    end

    def crop_ratio
      @crop_ratio = 0
    end

    def customer_params
      params.require(:customer).permit(*Customer.globalize_attribute_names, photos_attributes: [:id, :pics, :_destroy, :customer_id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/customers/_form.html.erb
<div class="content-container">
  <%= nested_form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>
        <ul>
        <% @customer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="customer-logo-field">
      <%= f.label :photos, "부수 사진" %>
      <%= f.fields_for :photos do |pf| %>
        <%= pf.file_field :pics, class: "photoInfo" %>
        <%= pf.link_to_remove "삭제하기", class: "photoButton", type: "remove" %>
      <% end %>
      <%= f.link_to_add "추가하기", :photos, class: "photoButton", type: "add" %>
    </div>
    <div class="customer-name-field">
      <%= f.label :name_ko, "한글 이름" %>
      <%= f.text_field :name_ko %>
      <%= f.label :name_en, "영문 이름" %>
      <%= f.text_field :name_en %>
    </div>
    <div class="customer-submit-field">
      <%= f.submit "등록하기" %>
    </div>
  <% end %>
</div>

app/views/customers/admin_index.html.erb
<div class="content-container">
  <h1>고객들</h1>
  <%= link_to "고객 추가", new_customer_path %>
  <table>
    <thead>
      <tr>
        <th>이름(링크)</th>
        <th>로고</th>
        <th>수정</th>
        <th>삭제</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.name %></td>
          <% unless customer.photos.empty? %>
            <% customer.photos.each do |photo| %>
              <td><%= image_tag photo.pics.url(:logo) %></td>
            <% end %>
          <% else %>
            <td>사진 없음</td>
          <% end %>
          <td><%= link_to("수정", edit_customer_path(customer)) %></td>
          <td><%= link_to("삭제", customer_path(customer) , method: :DELETE, data:{confirm: '정말로 삭제 하시겠습니까?'}) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/customers/admin_show.html.erb
<h1></h1>
<%= link_to "고객리스트로 가기", customers_admin_path %>
<% if admin_signed_in? %>
  |  <%= link_to "수정", edit_customer_path(@customer) %>
  |  <%= link_to "삭제", customer_path(@customer), method: :DELETE, data:{confirm: "선택하신 항목으 지우시겠습니까?"} %>
<% end %>
<div class="customer-index-container">
  <div class="customer-box">
    <div class="customer-logo">
      <% @customer.photos.each do |photo| %>
        <%= image_tag photo.pics.url(:logo) %>
      <% end %>
    </div>
    <div class="customer-name">
      <%= @customer.name %>
    </div>
  </div>
</div>

app/views/customers/crop.html.erb
<h1>이미지 사이즈 수정</h1>
<div class="photo-crop-area">
    <div class="cropping-area-container">
        <div class="cropping-area" id="cropping-area">    
            <%= image_tag @customer.pics_url(:raw), id: "cropping-image" %>
        </div>
        <%= form_for @customer do |f| %>
            <% %w[x y w h].each do |attribute| %>
                <%= f.hidden_field "crop_#{attribute}", id: "crop_#{attribute}" %>
            <% end %>
            <%= f.submit "등록하기"%>
        <% end %>
    </div>
</div>

<script>
$(document).on('turbolinks:load', function(){
    $("img#cropping-image").each(function(){
        croppingImage = $(this);
        croppingImage.Jcrop({
            aspectRatio: 1,
            setSelect: [0, 0, 300, 300],
            onChange: update_crop, 
            onSelect: update_crop
        });
        function update_crop(coords) {
          $("#crop_x").val(Math.round(coords.x));
          $("#crop_y").val(Math.round(coords.y));
          $("#crop_w").val(Math.round(coords.w));
          $("#crop_h").val(Math.round(coords.h));
        };
    });
});
</script>

app/views/customers/edit.html.erb
<%= link_to 'Back', customers_path %>

<h1>고객 정보 수정</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<div class="content-container customers">
  <div class="page-image-container">
    <div class="page-image customers">
      <h2 class="page-image-title"><%= title t(".title") %></h2>
    </div>
  </div>
  <h2 class="page-title"><%= title t(".title") %></h2>
  <div class="customer-index-container">
      <% @customers.each do |customer| %>
      <div class="customer-box">
        <div>
          <div class="customer-logo-and-name" data-style="display: flex;">
            <% customer.photos.each do |photo| %>
              <%= image_tag photo.pics.url(:logo), class: 'customer-logo', style: "-ms-transform: translateY(-50%);" %>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/customers/new.html.erb
<%= link_to 'Back', customers_path %>

<h1>새 고객 등록</h1>

<%= render 'form' %>

app/views/customers/show.html.erb
<h1></h1>
<%= link_to "인덱스로 가기", customers_path %>
<% if admin_signed_in? %>
  |  <%= link_to "수정", edit_customer_path(@customer) %>
  |  <%= link_to "삭제", customer_path(@customer), method: :DELETE, data:{confirm: "선택하신 항목으 지우시겠습니까?"} %>
<% end %>
<div class="customer-index-container">
  <div class="customer-box">
    <div class="customer-logo">
      <%= image_tag @customer.pics_url(:thumb)%>
    </div>
    <div class="customer-name">
      <%= @customer.name %>
    </div>
  </div>
</div>