config/routes.rb
Rails.application.routes.draw do
  
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :brands
    resources :product_types
    get 'admin_product_types' => 'product_types#admin_index', as: 'admin_product_types'
    resources :customers
    devise_for :admins
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :customers
    get 'customers_admin' => 'customers#admin_index', as: 'admin_customers'
    get 'customer_admin' => 'customers#admin_show', ad: 'admin_customer'
    resources :articles
    resources :photos
    resources :products
    resources :attachments, except: :show
    resources :marketapps, except: :show
    resources :histories, except: [:show, :index]
    #contact
    get 'contacts/new' => 'contacts#new', as: 'new_contact'
    post 'contacts' => 'contacts#create', as: 'contacts'
    # product browser
    get 'product-browser' => 'product_browser#browser', as: 'pb'
    get 'product-browser/product-type/:id' => 'product_browser#product_types', as: 'pb_pt'
    get 'product-browser/brand/:id' => 'product_browser#brands', as: 'pb_b'



    # pages
    # the code right below is alternative to %get 'pages/home' => 'pages#home', as: "home"%
    root 'pages#home'
    get 'pages/about-us' => 'pages#aboutUs', as: 'about_us'
    get 'pages/a-letter-from-the-ceo' => 'pages#ceoLetter', as: 'ceo_letter'
    get 'pages/company-history' => 'histories#index', as: 'company_history'
    get 'pages/contact-us' => 'pages#contactUs', as: 'contact_us'
    get 'pages/careers' => 'pages#careers', as: 'careers'
    get 'pages/locations' => 'pages#locations', as: 'locations'
    get 'pages/downloads' => 'pages#downloads', as: 'downloads'
    get 'pages/downloads_search' => 'pages#downloads_search', as: 'downloads_search'
    get 'pages/search' => 'pages#search', as: 'search'

    # markets
    get 'markets/' => 'markets#index', as: 'allMarkets'

    # heritages link
    get 'heritages/:heritage' => 'products#index', as: :heritage

    # locale redirect
    get "*path", to: "pages#not_found"
  end

  # locale redirect
  get '*path', to: redirect("/#{I18n.default_locale}/%{path}")
  get '', to: redirect("/#{I18n.default_locale}/")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :recoverable,
          :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  # photo
  has_many :photos, as: :images ,dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true
  # validation
  validates :title, :summary, presence: true
  # globalize
  translates :title, :string
  translates :summary, :text
  # globalize form attr
  globalize_accessors attributes: [:title, :summary]
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  mount_uploader :file_path, FileUploader
end

app/models/brand.rb
class Brand < ActiveRecord::Base
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    has_many :brand_product_types, dependent: :destroy
    has_many :product_types, through: :brand_product_types
    has_many :products, through: :product_types
    validates :name, presence: true
    validates :photos, presence: true
    validates :background_pic, presence: true

    mount_uploader :background_pic, PicsUploader

    attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
    def title
        self.name
    end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :photos, as: :images, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true

  validates :name, :presence => true
  validates :name, :uniqueness => true

  # globalize
  translates :name, :string
  # globalize form attr
  globalize_accessors :locales => [:en, :ko], :attributes => [:name]

end

app/models/history.rb
class History < ApplicationRecord
    # validation
    validates :title, :event_date, presence: true
    # globalize
    translates :title, :string
    # globalize form attr
    globalize_accessors attributes: [:title]
end

app/models/market.rb
class Market < ApplicationRecord
  has_many :marketapps
  translates :name, :string
  globalize_accessors attributes: [:name]

  mount_uploader :banner, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
end

app/models/marketapp.rb
class Marketapp < ApplicationRecord
  belongs_to :market
  translates :name, :string
  globalize_accessors attributes: [:name]

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :images, polymorphic: :true
  
  mount_uploader :pics, PicsUploader
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_pics

  def crop_pics
    pics.recreate_versions! if crop_x.present?
    puts 'pics recreated'
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_type
  belongs_to :brand
  has_many :photos, as: :images, dependent: :destroy
  has_many :subproducts

  # # globalize
  # translates :name, :string
  # translates :summary, :text
  # # globalize form attr
  # globalize_accessors attributes: [:name, :summary]
end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
    has_many :brand_product_types
    has_many :brands, :through => :brand_product_types
    has_many :products
    has_many :photos, as: :images, dependent: :destroy
    accepts_nested_attributes_for :photos, allow_destroy: true

    validates :name, presence: true

    # globalize
    translates :name, :string
    # globalize form attr
    globalize_accessors attributes: [:name]

end

app/models/subproduct.rb
class Subproduct < ActiveRecord::Base
  belongs_to :product
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :to_crop_obj, only: [:edit, :update]
  before_action :crop_ratio, only: [:create, :update]
  before_action :authenticate_admin!, except: [:show, :index]
  before_action :all_product_types, only: [:new, :edit]

  # GET /brands
  def index
    @brands = Brand.all
  end

  # GET /brands/1
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  def create
    @brand = Brand.new(brand_params)
    if @brand.save
      if @brand.photos.present?
        @crop_obj = @brand
        render "shared/crop"
      else
        redirect_to @brand
      end
    else
      render :new
    end
  end

  # PATCH/PUT /brands/1
  def update
    if @brand.update(brand_params)
      if @brand.photos.present?
        render "shared/crop"
      else
        redirect_to @brand
      end
    else
      render :edit
    end
  end
  def crop

  end
  # DELETE /brands/1
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    def to_crop_obj
      @crop_obj = @brand
    end

    def crop_ratio
      @crop_ratio = 0
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.require(:brand).permit(:name, :url, :background_pic, {photos_attributes: [:id, :pics, :_destroy, :brand_id]}, {product_type_ids: []})
    end

    def all_product_types
      @productTypeAll = ProductType.all
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/brands/_form.html.erb
<%= nested_form_for(@brand) do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, id: "text_field" %>
  </div>
  <div class="field">
    <%= f.label :photos, "로고 사진 (사진 추가시 등록후 사이즈 조정 페이지로 넘어감.)" %>
    <%= f.fields_for :photos do |pf| %>
      <%= pf.file_field :pics, class: "photoInfo" %>
      <%= pf.link_to_remove "삭제하기", class: "photoButton button", type: "remove" %>
    <% end %>
    <%= f.link_to_add "추가하기", :photos, class: "photoButton button", type: "remove" %>
  </div>
  <div class="field">
    <p>사진의 높이(height) 와 폭(width)의 비율은 1.1 이여야 합니다<i>예)높이/폭 -> 1.1 </i></p>
    <%= f.label :background_pic,"제품페이지 배경 사진" %>
    <%= f.file_field :background_pic %>
  </div>
  
  <div class="actions">
    <%= f.submit "등록하기", class: "button" %>
  </div>
<% end %>

app/views/brands/edit.html.erb
<h1>브랜드 수정</h1>

<%= render 'form' %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

app/views/brands/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brands List</h1>
<% if admin_signed_in? %>
  <%= link_to "브랜드 추가", new_brand_path %>
<% end %>
<table>
  <thead>
    <tr>
      <th>이름</th>
      <th>로고</th>
      <th>제품 페이지 배경</th>
      <th colspan="2">액션</th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= link_to brand.name, brand %></td>
        <td>
          <% if brand.photos.present? %>
            <% brand.photos.each do |photo| %>
              <%= image_tag photo.pics.url(:logo), class: 'brand-logo', style: "-ms-transform: translateY(-50%);" %>
            <% end %>
          <% else %>
            무
          <% end %>
        </td>
        <td>
          <% if brand.background_pic.present? %>
            <div>
              <%= image_tag brand.background_pic_url(:large) %>
            </div>
          <% else %>
            무
          <% end %>
        </td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/new.html.erb
<h1>새 브랜드 등록</h1>

<%= render 'form' %>

<%= link_to 'Back', brands_path %>

app/views/brands/show.html.erb
<%= link_to("브랜드 리스트로 가기", brands_path) %> |
<% if admin_signed_in? %>
  <%= link_to("수정", edit_brand_path(@brand)) %> |
  <%= link_to("삭제", brand_path(@brand) , data: {confirm: "해당 브랜드를 정말 삭제 하시겠습니까?"}) %>
<% end %>

<fieldset>
  <h3><%= @brand.name %></h3>
  <% @brand.photos.each do |photo| %>
    <%= image_tag photo.pics.url(:logo) %>
  <% end %>
  <div>
    <%= image_tag @brand.background_pic_url(:large) %>
  </div>
</fieldset>

app/views/brands/show.js.erb
$('#brands_products_container').addClass('brand_activated');
$('#products_container').html("<%= j render(:partial => "show_products")%>");